---

- include_role: name=nbz4live.php-fpm private=true
  vars:
    php_fpm_version: "{{ invoiceninja_fpm_php_version }}"
    php_fpm_apt_packages: '{{ invoiceninja_php_packages }}'
    php_fpm_ini: '{{ invoiceninja_fpm_ini }}'
    php_fpm_pools: '{{ invoiceninja_php_fpm_pools }}'
