---

- name: Clone the git repo for Invoice Ninja
  git:
    accept_hostkey: 'yes'
    repo: '{{ invoiceninja_repo }}'
    dest: '{{ invoiceninja_path }}/{{ invoiceninja_user }}'
  become: 'yes'
  become_user: '{{ invoiceninja_user }}'

- name: Composer install Invoice Ninja dependencies
  composer:
    command: install
    working_dir: '{{ invoiceninja_path }}/{{ invoiceninja_user }}'

- name: Configure env
  template:
    src: env.j2
    dest: '{{ invoiceninja_path }}/{{ invoiceninja_user }}/.env'
  become: 'yes'
  become_user: '{{ invoiceninja_user }}'
