---

- import_tasks: dependencies.yml

- import_tasks: fpm.yml
  when: invoiceninja_fpm_install

- import_tasks: install.yml

- import_tasks: mysql.yml
  when: invoiceninja_mysql_install

- import_tasks: nginx.yml
  when: invoiceninja_nginx_install
