---

- include: dependencies.yml

- include: fpm.yml
  when: invoiceninja_fpm_install

- include: install.yml

- include: mysql.yml
  when: invoiceninja_mysql_install

- include: nginx.yml
  when: invoiceninja_nginx_install
